#!/bin/sh

set -x

CURRENT_DIR=`pwd`
SOURCE_DIR=${SOURCE_DIR:-${CURRENT_DIR}/src}
BUILD_DIR=${BUILD_DIR:-./build}
BUILD_TYPE=${BUILD_TYPE:-release}
INSTALL_DIR=${INSTALL_DIR:-./${BUILD_TYPE}}
CXX=${CXX:-g++}

mkdir -p $BUILD_DIR/$BUILD_TYPE \
  && cd $BUILD_DIR/$BUILD_TYPE \
  && cmake \
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
      -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      $SOURCE_DIR \
  && make install
